create table public.industrial_properties (
  property_id serial not null,
  listing_id character varying(50) not null,
  property_segment character varying(50) not null,
  listing_type character varying(20) not null,
  main_category character varying(50) not null,
  sub_category character varying(50) not null,
  status character varying(20) not null default 'active'::character varying,
  description text null,
  price numeric(15, 2) not null,
  area_size numeric(10, 2) not null,
  area_ppsf numeric(10, 2) null,
  district_number integer null,
  postal_code character varying(10) null,
  latitude double precision null,
  longitude double precision null,
  address_name text null,
  closest_mrt character varying(100) null,
  photo_url text null,
  listing_url text null,
  location geography null,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  planning_area text null,
  subzone text null,
  constraint industrial_properties_pkey primary key (property_id),
  constraint industrial_properties_listing_id_key unique (listing_id)
) TABLESPACE pg_default;