create table public.demographics_housing_types (
  id bigint generated by default as identity not null,
  subzone text null,
  planning_area text null,
  hdb_2_room text null,
  hdb_3_room text null,
  hdb_4_room text null,
  hdb_5_room_ea text null,
  condominiums_and_apartments text null,
  landed_properties text null,
  other_types_properties text null,
  constraint demographics_housing_types_pkey primary key (id)
) TABLESPACE pg_default;