create table public.demographics_population (
  id bigint generated by default as identity not null,
  subzone text null,
  planning_area text null,
  population_chinese_male text null,
  population_chinese_female text null,
  population_malays_male text null,
  population_malays_female text null,
  population_indians_male text null,
  population_indians_female text null,
  population_others_male text null,
  population_others_female text null,
  subzone_size text null,
  population_density text null,
  constraint demographics_population_pkey primary key (id)
) TABLESPACE pg_default;